### ISSUE TITLE
My Favorite API Tools

### ISSUE THREAD

**Issue by ecaron** [minnesota-apis/topics#16]
> John Sheehan, CEO of Runscope, will be presenting his favorite API tools. Quoting his unbridled eloquence: "[It] won't be a pitch for Runscope, promise. I have a bunch of others I'll cover. Almost all are free."

http://www.meetup.com/Minnesota-API-Developers-Group/events/231076166/
July 19th, 2016

**Comment by johnsheehan** [comment]
Slides: https://speakerdeck.com/johnsheehan/my-favorite-api-tools-other-than-runscope
